### ISSUE TITLE
Unify color palette between calendar and announcements tab

### ISSUE THREAD

**Issue by konnork** [mhacks/MHacks-iOS#13]
Prefer Calendar color palette
- Factor colors into a Colors.swift file and have both calendar and announcements tab pull from there
- Color corresponds to category

Logic:
- Every category besides sponsored gets a color
- Every event will belong to 0 or 1 "normal" categories and optionally the sponsored category
- No category + No sponsored: gray bar, no badge
- No category + Sponsored: gray bar, badge
- Category + No sponsored: colored bar, no badge
- Category + Sponsored: colored bar, badge

**Comment by manavgabhawala** [comment]
Fixed with 82d568421df403d923e71efd4453c90f8df66ec7
