### ISSUE TITLE
Startup Flicker

### ISSUE THREAD

**Issue by manavgabhawala** [mhacks/MHacks-iOS#2]
On startup the page goes to yellow and there's a slight flicker to white before presenting the startup animation, this needs to be fixed.

**Comment by russellladd** [comment]
Can we just get rid of the startup animation? It goes against iOS Design Guidelines and IMO makes for a bad user experience. The icon is supposed to be branding enough.

**Comment by manavgabhawala** [comment]
We could get rid of it, I don't know about a bad user experience it looks kinda cool and lasts only about a couple seconds (maybe could make it shorter) and only when opening from a closed state. There are a decent amount of apps that use startup animations including Uber. But I'm not against ditching it completely.

**Comment by russellladd** [comment]
Uber takes an eternity to open and I hope for their sake its a loading animation and not a predefined one. Moreover, when I only want to check something in the app for a few seconds (which is most of my uses), a launch animation of a few seconds can be half my time in the app.

Please read Apple's guidelines on the launch experience here: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LaunchImages.html#//apple_ref/doc/uid/TP40006556-CH22-SW1

**Comment by manavgabhawala** [comment]
Resolved with [de2213c33d22523c006d4b1edf06f5125f231963](https://github.com/mhacks/MHacks-iOS/commit/de2213c33d22523c006d4b1edf06f5125f231963)
