### ISSUE TITLE
User Authentication Not Working

### ISSUE THREAD

**Issue by maxmatthews** [mhacks/MHacks-iOS#24]
I'm having a problem signing into the iOS app v.4.0.1. The email and password work fine on mhacks.org, but gives me an Invalid Password error in the app. Could potentially be because I have special characters in my password.

If you give me a little guidance. it's possible I could do a pull request.

**Comment by manavgabhawala** [comment]
What kind of special characters do you have? I don't think that's the issue. Are you copy pasting your password?

**Comment by maxmatthews** [comment]
Copy and pasting my password and pasting it works on mhacks.org http://mhacks.org/. My password has -+%*"[} plus upper and lowercase and numbers. My password manager randomly generated it.

**Comment by manavgabhawala** [comment]
That's really strange it really should be working. In any case if you can't get it to work I think for now you can just change your password.
